### ISSUE TITLE
The unbloced stuff

### ISSUE THREAD

**Issue by Redwhitedragen** [xploitspeeds/Bookmarklet-Hacks-For-School#2]
Hey, can you change it to where it says unbloc   k   ed to unbloced? My school filters the word so you can't enter websites with that word.

**Comment by Redwhitedragen** [comment]
nevermid, i forgot i could just download the zip lmao

**Comment by xploitspeeds** [comment]
> Hey, can you change it to where it says unbloc k ed to unbloced? My school filters the word so you can't enter websites with that word.

same, i think i'll do that
