### ISSUE TITLE
I want to add my zearn hacks

### ISSUE THREAD

**Issue by CryptoDude3** [xploitspeeds/Bookmarklet-Hacks-For-School#9]
can you add this: https://pastebin.com/KxN2hzaH

**Comment by pman5534** [comment]
zearn hack not work :(

**Comment by bensimms1** [comment]
I know, it used to at the time of posting. I'm working on a tower of power hack, since they patched the learning lab hack.

**Comment by bensimms1** [comment]
Here's the new zearn hacks(expect some more updates):
https://pastebin.com/yYXvJ7vj

**Comment by Calep-playz** [comment]
all hacks on github and pastebin do not work with javascript: or bookmark

**Comment by bensimms1** [comment]
They got patched like a week and a half ago agian

**Comment by bubbaontop** [comment]
FIXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX PLSSSSSSS I BEG

**Comment by bensimms1** [comment]
check them, just fixed them 2 ish hours ago

**Comment by bubbaontop** [comment]
alr

**Comment by bubbaontop** [comment]
YOUR A LIAR,ITS NOT EVEN YOUR HACKS

**Comment by bubbaontop** [comment]
ITS SOMEONE ELSE

**Comment by bubbaontop** [comment]
also like my name? Isint bubba such a beautiful name lol

**Comment by bensimms1** [comment]
Check my yt channel @ducklife3141 imma put a link to github in my about
channel

**Comment by bensimms1** [comment]
check the yt channel that made the original zearn hacks you'll see a link
to my github in the description

**Comment by bubbaontop** [comment]
how do i know your not lying, because I already subbed to ducklife

**Comment by bubbaontop** [comment]
you could have just put the link to someone else's in the desc

**Comment by bensimms1** [comment]
Because why would "the owner of duckllife" have a link to my github in the
about section

**Comment by Swagboiontop** [comment]
OR WHY WOULD YOU HAVE A LINK TO HIS GITHUB

**Comment by Swagboiontop** [comment]
i asked the guy privatly if your the same guy on pastebin and he said no

**Comment by Swagboiontop** [comment]
what u got to say about that liar?????????

**Comment by Swagboiontop** [comment]
EXACTLY BRO IS AS QUEIT AS THE MIDNIGHT SKY

**Comment by CryptoDude3** [comment]
Check the pastebin and look very closely at the bottom:
https://pastebin.com/yYXvJ7vj

**Comment by Swagboiontop** [comment]
What about the view count? and how am i making stuff up. are u a little mental?? u keep posting the link for someone else's pastebin...LOL stop trying to pass it off as your own.

**Comment by Swagboiontop** [comment]
LOLLLLLLLLLLL GET PRANKED DUCKLIFEEE AHAHHAHAHAHAHAHA IK IT WAS U THE WHOLE TIME I WANTED TO PRANK U

**Comment by Swagboiontop** [comment]
lol, i was joking the whole time

**Comment by Swagboiontop** [comment]
lol

**Comment by Swagboiontop** [comment]
it so great to meet a youtuber btw

**Comment by Swagboiontop** [comment]
in your next vid can u do a shoutout?

**Comment by CryptoDude3** [comment]
Lol it was pretty convincing.

**Comment by Swagboiontop** [comment]
thank you lol

**Comment by Swagboiontop** [comment]
yoooo what happend to the pastebin???????????????????

**Comment by Swagboiontop** [comment]
@CryptoDude3  PASTEBIN NOT WORKING, I NEED THE ZEARN HACKS

**Comment by CryptoDude3** [comment]
I just checked, they're working. when u say pastebin, do u mean the link,
or the actual hack? the universal ones are working perfectly. I can send u
another link if the current one isn't loading

**Comment by Swagboiontop** [comment]
No i mean like at the time of that i commented Pastebin was not working. Like i could not even load into Pastebin. But now everything works! Thanks.

**Comment by 86868686j** [comment]
Can you add A video to show how to install it please

**Comment by Ijustneedsomescripts** [comment]
Doesn't work on tower of power anymore :(
